/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminMasterRouteImport } from './routes/admin-master'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated.vehicles'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated.supervisor'
import { Route as AuthenticatedSupervisionRouteImport } from './routes/_authenticated.supervision'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRgRouteImport } from './routes/_authenticated.rg'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated.pending'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated.map'
import { Route as AuthenticatedFieldWorkListRouteImport } from './routes/_authenticated.field-work-list'
import { Route as AuthenticatedFieldWorkRouteImport } from './routes/_authenticated.field-work'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCyclesRouteImport } from './routes/_authenticated.cycles'
import { Route as AuthenticatedCoordenadorRouteImport } from './routes/_authenticated.coordenador'
import { Route as AuthenticatedAgenteRouteImport } from './routes/_authenticated.agente'
import { Route as AuthenticatedPropertyPropertyIdRouteImport } from './routes/_authenticated.property.$propertyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterRoute = AdminMasterRouteImport.update({
  id: '/admin-master',
  path: '/admin-master',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupervisionRoute =
  AuthenticatedSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRgRoute = AuthenticatedRgRouteImport.update({
  id: '/rg',
  path: '/rg',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFieldWorkListRoute =
  AuthenticatedFieldWorkListRouteImport.update({
    id: '/field-work-list',
    path: '/field-work-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFieldWorkRoute = AuthenticatedFieldWorkRouteImport.update({
  id: '/field-work',
  path: '/field-work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCyclesRoute = AuthenticatedCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoordenadorRoute =
  AuthenticatedCoordenadorRouteImport.update({
    id: '/coordenador',
    path: '/coordenador',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgenteRoute = AuthenticatedAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertyPropertyIdRoute =
  AuthenticatedPropertyPropertyIdRouteImport.update({
    id: '/property/$propertyId',
    path: '/property/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin-master': typeof AdminMasterRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/coordenador': typeof AuthenticatedCoordenadorRoute
  '/cycles': typeof AuthenticatedCyclesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/field-work': typeof AuthenticatedFieldWorkRoute
  '/field-work-list': typeof AuthenticatedFieldWorkListRoute
  '/map': typeof AuthenticatedMapRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rg': typeof AuthenticatedRgRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
}
export interface FileRoutesByTo {
  '/admin-master': typeof AdminMasterRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/coordenador': typeof AuthenticatedCoordenadorRoute
  '/cycles': typeof AuthenticatedCyclesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/field-work': typeof AuthenticatedFieldWorkRoute
  '/field-work-list': typeof AuthenticatedFieldWorkListRoute
  '/map': typeof AuthenticatedMapRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rg': typeof AuthenticatedRgRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/': typeof AuthenticatedIndexRoute
  '/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-master': typeof AdminMasterRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agente': typeof AuthenticatedAgenteRoute
  '/_authenticated/coordenador': typeof AuthenticatedCoordenadorRoute
  '/_authenticated/cycles': typeof AuthenticatedCyclesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/field-work': typeof AuthenticatedFieldWorkRoute
  '/_authenticated/field-work-list': typeof AuthenticatedFieldWorkListRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rg': typeof AuthenticatedRgRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supervision': typeof AuthenticatedSupervisionRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-master'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/agente'
    | '/coordenador'
    | '/cycles'
    | '/dashboard'
    | '/field-work'
    | '/field-work-list'
    | '/map'
    | '/pending'
    | '/reports'
    | '/rg'
    | '/settings'
    | '/supervision'
    | '/supervisor'
    | '/vehicles'
    | '/property/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin-master'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/agente'
    | '/coordenador'
    | '/cycles'
    | '/dashboard'
    | '/field-work'
    | '/field-work-list'
    | '/map'
    | '/pending'
    | '/reports'
    | '/rg'
    | '/settings'
    | '/supervision'
    | '/supervisor'
    | '/vehicles'
    | '/'
    | '/property/$propertyId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin-master'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/_authenticated/agente'
    | '/_authenticated/coordenador'
    | '/_authenticated/cycles'
    | '/_authenticated/dashboard'
    | '/_authenticated/field-work'
    | '/_authenticated/field-work-list'
    | '/_authenticated/map'
    | '/_authenticated/pending'
    | '/_authenticated/reports'
    | '/_authenticated/rg'
    | '/_authenticated/settings'
    | '/_authenticated/supervision'
    | '/_authenticated/supervisor'
    | '/_authenticated/vehicles'
    | '/_authenticated/'
    | '/_authenticated/property/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminMasterRoute: typeof AdminMasterRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-master': {
      id: '/admin-master'
      path: '/admin-master'
      fullPath: '/admin-master'
      preLoaderRoute: typeof AdminMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supervision': {
      id: '/_authenticated/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof AuthenticatedSupervisionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rg': {
      id: '/_authenticated/rg'
      path: '/rg'
      fullPath: '/rg'
      preLoaderRoute: typeof AuthenticatedRgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/field-work-list': {
      id: '/_authenticated/field-work-list'
      path: '/field-work-list'
      fullPath: '/field-work-list'
      preLoaderRoute: typeof AuthenticatedFieldWorkListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/field-work': {
      id: '/_authenticated/field-work'
      path: '/field-work'
      fullPath: '/field-work'
      preLoaderRoute: typeof AuthenticatedFieldWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cycles': {
      id: '/_authenticated/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AuthenticatedCyclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordenador': {
      id: '/_authenticated/coordenador'
      path: '/coordenador'
      fullPath: '/coordenador'
      preLoaderRoute: typeof AuthenticatedCoordenadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agente': {
      id: '/_authenticated/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AuthenticatedAgenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/property/$propertyId': {
      id: '/_authenticated/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertyPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgenteRoute: typeof AuthenticatedAgenteRoute
  AuthenticatedCoordenadorRoute: typeof AuthenticatedCoordenadorRoute
  AuthenticatedCyclesRoute: typeof AuthenticatedCyclesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFieldWorkRoute: typeof AuthenticatedFieldWorkRoute
  AuthenticatedFieldWorkListRoute: typeof AuthenticatedFieldWorkListRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRgRoute: typeof AuthenticatedRgRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupervisionRoute: typeof AuthenticatedSupervisionRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPropertyPropertyIdRoute: typeof AuthenticatedPropertyPropertyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgenteRoute: AuthenticatedAgenteRoute,
  AuthenticatedCoordenadorRoute: AuthenticatedCoordenadorRoute,
  AuthenticatedCyclesRoute: AuthenticatedCyclesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFieldWorkRoute: AuthenticatedFieldWorkRoute,
  AuthenticatedFieldWorkListRoute: AuthenticatedFieldWorkListRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRgRoute: AuthenticatedRgRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupervisionRoute: AuthenticatedSupervisionRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPropertyPropertyIdRoute: AuthenticatedPropertyPropertyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminMasterRoute: AdminMasterRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
