ALTER TABLE public.daily_work_records
  ADD COLUMN IF NOT EXISTS strategic_points_worked INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tubitos_used INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS larvae_collected INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cargas_collected INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS foci_by_type JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS deposits_by_type JSONB NOT NULL DEFAULT '{}'::jsonb;